
---

- hosts: all
  become: true
  tasks:
 
  - name: installing apache package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"    
  - name: update cache
    apt:
      update_cache: true 
