
---

- hosts: all
  tags: always
  become: true
  gather_facts: no
  tasks:
 
  - name: installing apache package
    apt:
      name: apache2
      state: latest


- hosts: server_1
  tags: server1
  become: true
  tasks:

  - name: update cache
    apt:
      update_cache: true
  
  - name: copy files
    tags: copy
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: server_2
  tags: server2
  become: true
  tasks: 

  - name: install samba  package
    package: 
      name: samba
      state: latest

